### PR TITLE
Add WINTER

### PR DESCRIPTION
**Pull request by virajkaram**
This PR updates a few config files to 
1. Add WINTER/SUMMER instruments on Fritz
2. Add a WINTER alert stream
3. Include WINTER in the kowalski section of fritz.defaults.yaml (essentially replaces the existing section with [this](https://github.com/skyportal/kowalski/blob/master/config.defaults.yaml)
4. Pins kowalski and skyportal to versions that include WINTER

### CODE REVIEW

**Review by guynir42 — APPROVED** [review]
Looks fine. We should do a thorough check that this works on staging.

**Comment by mcoughlin** [comment]
@virajkaram Looks like you may have forgotten the pre commit.

**Comment by virajkaram** [comment]
> 

@mcoughlin oops, fixed it, sorry!

**Comment by virajkaram** [comment]
@mcoughlin I updated the SP pin and it passed all the pre-commits locally so hopefully that fixed it. Can you take a look now please?

**Comment by mcoughlin** [comment]
@virajkaram Clearly it is still an issue. Could you undo your skyportal pin? We usually pin skyportal in separate commits when we deploy.

**Pull request merged**
