### PR TITLE
Update fritz config with analysis paths

### PR DESCRIPTION
**Pull request by mcoughlin**
This PR adds the analysis paths to the fritz config.

### CODE REVIEW

**Review by guynir42 — APPROVED** [review]
Were there no changes to the source page as well?

**Comment by mcoughlin** [comment]
@guynir42 that will come once the SP PR is merged.

**Comment by guynir42** [comment]
@mcoughlin does it make sense to merge this before the SP PRs are in?

**Comment by guynir42** [comment]
What I'm wondering is would it be useful to the users to have an analysis page if they don't have all the tools to run it on objects. Is the analysis page usable on its own?

**Comment by mcoughlin** [comment]
@guynir42 Yes. This deals with the concept of an analysis service. The other PR adds a front end to trigger them (but API still is fine).

**Pull request merged**
