### PR TITLE
pin fritz to version of skyportal with slack integration

### PR DESCRIPTION
**Pull request by dannygoldstein**
This enables slack integration and relaxes strict permission checking on skyportal

### CODE REVIEW

**Comment by acrellin** [comment]
Looks like an invalid SP commit is pinned or something?

**Review by kmshin1397 — APPROVED** [review]

**Review by acrellin — COMMENTED** [review]
@dannygoldstein where are you going to change the config security settings to not strict? In fritz-deploy?

**Comment by dannygoldstein** [comment]
@acrellin , yep, that's done here:

https://github.com/fritz-marshal/fritz-deploy/commit/ac53dd9db72ffc8faea0b2e456f53ca3a60ca803

**Review by acrellin — APPROVED** [review]
Esp as this is just temporary, I'm good with it. @dannygoldstein let's just make sure staging looks good before we deploy to production

**Pull request merged**
