### PR TITLE
Update SkyPortal and Kowalski

### PR DESCRIPTION
**Pull request by acrellin**

### CODE REVIEW

**Comment by dmitryduev** [comment]
@acrellin the make run command wouldn't install all the deps inside the SP docker container for some reason; the action is killed after 30 minutes. Trying to rerun it now, will see if it was intermittent. Have you checked if it builds locally?

**Comment by acrellin** [comment]
@dmitryduev rerunning again; I unfortunately haven't been able to build locally for a while. Has it ever been passing recently?

**Comment by dmitryduev** [comment]
yea, it's been green for a while, haven't had problems for like a couple months!

**Comment by dmitryduev** [comment]
what are you seeing locally?

**Comment by acrellin** [comment]
Some config key error

**Comment by acrellin** [comment]
"Fix config.yaml..."

**Comment by acrellin** [comment]
Also, when trying to prune, 
```
  File "/home/arien/projects/fritz/launcher/commands/prune.py", line 21, in prune 
    stop()                                                                        
TypeError: 'module' object is not callable                                        

```

**Comment by dmitryduev** [comment]
@acrellin just `rm -f fritz.yaml` (and prob also ./fritz prune to clean up everything). when you `./fritz run --init --yes` afterward it'll use the default config.

as for the issue in `prune.py`, I have exactly the same problem. In fact, I tried committing the fix (change line 3 in that file to `from launcher.commands.stop import stop`), but @stefanv keeps rolling it back 🤣 I was unable to figure out why it's so, so I have an uncommitted version of that file locally to make it work lol.

**Comment by stefanv** [comment]
Happy to merge the correct patch :)

**Comment by dmitryduev** [comment]
Closing in favor of #355.

**Pull request closed without merging**
