### PR TITLE
add sentry

### PR DESCRIPTION
**Pull request by dannygoldstein**
This PR adds sentry logging of all skyportal API errors, showing the request payload, the request that errored, and the user

### CODE REVIEW

**Comment by dannygoldstein** [comment]
@dmitryduev How can I introspect / understand why the CI is failing here

**Comment by profjsb** [comment]
@dannygoldstein what's the URL in the config pointing to? Is it a dummy link? We don't want all Fritz instances pointing to our sentry endpoint right? Does it need to be in secrets?

**Comment by dannygoldstein** [comment]
No its a real link. Yeah, we should probably move it to secrets in fritz-deploy.

**Comment by dmitryduev** [comment]
@dannygoldstein there was an issue with the sp image build due to a dependency clash, which @acrellin resolved yesterday. Please pull in the latest master, should work now.

**Comment by profjsb** [comment]
> No its a real link. Yeah, we should probably move it to secrets in fritz-deploy.

I'll re-review once the link is moved to the secrets file.

**Comment by acrellin** [comment]
@profjsb @dmitryduev  sentry secret removed here and added to secrets file in fritz-deploy

**Comment by guynir42** [comment]
@profjsb any thoughts on this?

**Comment by guynir42** [comment]
@profjsb Do you have any idea if this is still relevant?

**Pull request closed without merging**
