### PR TITLE
Docs GA

### PR DESCRIPTION
**Pull request by Theodlz**
An attempt at fixing the GA that generates the docs. Currently we have a couple of issues getting the python env to work

### CODE REVIEW

**Comment by Theodlz** [comment]
pausing this PR while I update a bunch of SkyPortal dependencies to avoid conflicts with those pinned in Kowalski

**Comment by Theodlz** [comment]
in the mean time (so I can keep trying to fix the rest), not referencing ALL the Kowalski dependencies in Fritz's requirements.txt

**Comment by Theodlz** [comment]
also started to fix the integration tests but those need more work, however the main goal of this PR (fix the docs) is achieved and this can be merged

**Review by mcoughlin — APPROVED** [review]
LGTM

**Pull request merged**
