### PR TITLE
TNS cross-match data

### PR DESCRIPTION
**Pull request by dmitryduev**
In this PR:

- In `/api/alerts/ztf/<oid>/aux`, run a cone search on the TNS collection on Kowalski and report the results as a part of the `cross_matches` field.

tns-x-match

### CODE REVIEW

**Review by dannygoldstein — CHANGES_REQUESTED** [review]
Can we do this through the new fritz extension strategy?

**Comment by dmitryduev** [comment]
@dannygoldstein I'd merge this in and do the migration to the new strategy in the next PR, please.

**Review by kmshin1397 — APPROVED** [review]
LGTM! One quick question - why did you remove the `async` on the GET handler? I don't think I saw anything that required making it synchronous explicitly but that may just be me not being as familiar with K

**Review by dannygoldstein — APPROVED** [review]

**Comment by dmitryduev** [comment]
@kmshin1397 re your question: it's actually `self.finish()` that would require awaiting should I keep the get def async, so since nothing is really async in this method, I decided to remove it for now.

**Pull request merged**
