### PR TITLE
Add num alerts ingested today to DB Stats handler info

### PR DESCRIPTION
**Pull request by acrellin**
The front-end component already renders arbitrary data, so no update needed there

See #162

### CODE REVIEW

**Review by dmitryduev — APPROVED** [review]
:+1:

**Comment by dmitryduev** [comment]
Once #153 is merged, the CI should turn green here, then will merge.

**Comment by acrellin** [comment]
I just realized we need to merge https://github.com/skyportal/skyportal/pull/1685 and then update this PR before it goes in

**Comment by acrellin** [comment]
@dmitryduev it looks like I pinned the newest K version here -- any potential issues with that?

**Comment by acrellin** [comment]
When I run `black` on the modified file locally, it passes, but is complaining on GA  🤔

**Comment by acrellin** [comment]
When https://github.com/skyportal/skyportal/pull/1698 goes in, this will need to be updated again :sigh:

**Comment by dmitryduev** [comment]
@acrellin, ok to merge now?

**Comment by acrellin** [comment]
@dmitryduev yes, thanks!

**Pull request merged**
