### PR TITLE
Update SP & add rate-limiting params to config

### PR DESCRIPTION
**Pull request by acrellin**

### CODE REVIEW

**Review by dmitryduev — COMMENTED** [review]
Thanks a lot @acrellin! Looks like SP was still rate-limiting K's requests, see:
https://github.com/fritz-marshal/fritz/pull/316/checks?check_run_id=3107797626#step:7:2177

We may have to get the gateway IP address manually and propagate it into the config, see
https://github.com/fritz-marshal/fritz/blob/dd5f5bb1c77003f90a9c262b7d049f08027f1093/fritz#L116

Did the test pass locally? I'd make sure K's IP is within the whitelisted range...

**Comment by dmitryduev** [comment]
Ah, the fix could be as simple as pinning the latest K - could you please do that @acrellin?

**Comment by stefanv** [comment]
Should be safe to whitelist the following by default:

```
10.0.0.0/8
172.16.0.0/12
192.168.0.0/16
```

**Comment by acrellin** [comment]
@dmitryduev this already pins K d8c5a86

**Review by dmitryduev — APPROVED** [review]

**Pull request merged**
