### PR TITLE
Fix bug when searching alerts from source page

### PR DESCRIPTION
**Pull request by dmitryduev**
In this PR: 
- Addressed a bug where clicking on the Search ZTF Alert Archive on the Source Page didn't work.
- Rearranged the buttons on the Source page a bit so that they take less space.
search-alerts
- Fixed a bug in test_get_alert_cutout.

### CODE REVIEW

**Comment by acrellin** [comment]
What's the bug fix here? Removing the prop from `propTypes`?

**Comment by dmitryduev** [comment]
@acrellin my duck stupidly assumed that ra/dec/radius would only come from the alert page in the form of strings. I just fixed that assumption.

**Comment by dmitryduev** [comment]
This: https://github.com/fritz-marshal/fritz/pull/313/files#diff-1fdaef78be891e5f488d9148f5579148867874179a8fdcd117bd6e145e3b9a2cR11

**Comment by dmitryduev** [comment]
Hmm, failure on the CI looks real, never seen it before, and it happened in an unexpected place. Investigating.

**Review by acrellin — APPROVED** [review]

**Pull request merged**
