### PR TITLE
Make centroid plot size more responsive

### LINKED ISSUE #317: Fix updated Centroid plot size/CSS
**Describe the bug**
It's could be a bit off on some screens/some screen sizes, like this:
image

Need to fix that!

### PR DESCRIPTION
**Pull request by kmshin1397**
centroidplot

Closes #317

### CODE REVIEW

**Comment by profjsb** [comment]
Looks great. Have you confirmed that the responsiveness also extends to @dmitryduev's new value-enhanced offsets (nearby sources via Kowalski)?

**Review by dmitryduev — APPROVED** [review]
Many thanks @kmshin1397!! Would you mind also checking what happens when you zoom in/out the page?

**Comment by kmshin1397** [comment]
> Looks great. Have you confirmed that the responsiveness also extends to @dmitryduev's new value-enhanced offsets (nearby sources via Kowalski)?

@profjsb Yep, it should be the same behavior as they use the same div/CSS as in the screenshot. I just used the existing SP plot to test the tweaks here for faster iteration in development

**Comment by kmshin1397** [comment]
> Many thanks @kmshin1397!! Would you mind also checking what happens when you zoom in/out the page?

Seems like there aren't any issues with zooming:
zoom

**Comment by dmitryduev** [comment]
Will merge once green. The CI sometimes catches issues unrelated to a PR, like it did with the requests=2.26 update :)

**Pull request merged**
